### PR TITLE
Fixes for SEO with basename

### PR DESCRIPTION
**Pull request by re6exp**
Changed to match the _redux-first-router#**rudy**_ API.
_Notice:_ Need to create new branch in demo repository!

### CODE REVIEW

**Comment by faceyspacey** [comment]
Thanks for all this. Going through it now.

Why is the hmr changed, particularly to have reload=true?

Also, why do we need a peer dep of history? I'm thinking of removing it as a peer dep and removing its dep here.

**Comment by re6exp** [comment]
It's my fault, I overlooked that. I played with them and forgave to revert. Yep, it should be removed from there.

**Comment by faceyspacey** [comment]
ok this is done, it's now as the rudy branch here:

https://github.com/faceyspacey/redux-first-router-demo/tree/rudy

we'll merge to master when rudy is done. im going to close this PR as i did it separately since merging this would have merged to master. Thanks again!

**Comment by re6exp** [comment]
Thank you, James!

**Pull request closed without merging**
